apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-survey-app
  namespace: swe645
  labels:
    app: student-survey
spec:
  replicas: 3
  selector:
    matchLabels:
      app: student-survey
  template:
    metadata:
      labels:
        app: student-survey
    spec:
      containers:
      - name: student-survey
        image: gcr.io/alpine-beacon-473720-s5/student-survey:v2
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: student-survey-service
  namespace: swe645
spec:
  selector:
    app: student-survey
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer